subtitles/xue-yu/20190801-三轮车熏肉

https://github.com/immoonancient/YTSubtitles/issues/8

翻译稿 20190801-三轮车熏肉

---

subtitles/wang-gang/190809-xiufangzi

Create 190809-xiufangzi-quan-guo-chen 

---

subtitles/CODEOWNERS

Trevor同学已同意做reviewer，暂时不要merge，等待后续其他人答复

Update CODEOWNERS   *审核后可merge

---

subtitles/CODEOWNERS

Add @lolololol0122 to subtitles code owners

---

subtitles/hua-nong-brothers/first-heatstroke-video

華農兄弟第一次竹鼠中暑
https://www.youtube.com/watch?v=QseaTncWZuM&t=21s
同樣地.，我希望保留劉蘇良的"哎呀"  "咿喲" 之類的話
他那個"這個"  "那個"  如果不是用作指代詞的話，我會譯作  ....eh... 各位可提議其他譯法
謝！

華農兄弟第一次竹鼠中暑

---

subtitles/xue-yu/20190818-fu-jian-shi-hua-gao

Create 20190818 福建石花膏

---

subtitles/xue-yu/20190820-fu-jian-cu-rou

Create 20190820 福建醋肉

---

subtitles/wang-gang/20190822-bao-chao-tu-ji.sbv

20190822 爆炒土鸡

---

subtitles/wang-gang/20190823-ji-si-liang-mian

#92 
貌似遇到点技术问题，代 @StephanJia 上传

20190823 鸡丝凉面

---

subtitles/wang-gang/20190829-zha-feng-yong.sbv

Add comment marks to Chinese lines

---

subtitles/hua-nong-brothers/20190831-borrow-male-rats.sbv

20190831 華農兄弟借公鼠

---

subtitles/hua-nong-brothers/20190901-huanong-bunnies.sbv

https://www.youtube.com/watch?v=q5LIesnaRnw

華農兄弟 2019  兔子

---

subtitles/hua-nong-brothers/20190901-huanong-borrow-male-rats-2.sbv

https://www.youtube.com/watch?v=6oBeqQFSJZs&t=26s

華農兄弟  第二次借公鼠

---

tutorial/Commit-change.md

调整 Commit-change.md 格式

---

subtitles/hua-nong-brothers/20190903-chestnuts.sbv

[华农兄弟]打板粟 https://www.youtube.com/watch?v=RaO260yv_Gw

#145[华农兄弟]打板粟

---

subtitles/wang-gang/README.md

添加王刚翻译守则大纲

---

subtitles/wang-gang/20190901-ma-po-dou-fu.sbv

Add missing revisions to 麻婆豆腐

---

subtitles/wang-gang/20190907-Jiang-You-Chao-Fan

Create  20190907-Jiang-You-Chao-Fan

---

subtitles/hua-nong-brothers/20190908-Wanggang-chestnuts.sbv

#170 
https://www.youtube.com/watch?v=LxJsZk0B454

#170 带王刚摘板栗

---

subtitles/hua-nong-brothers/20190910-chicken-flower.sbv

#175 https://www.youtube.com/watch?v=rxMTlq_mTXE

#175   木槿花

---

subtitles/hua-nong-brothers/20190915-check-rats.sbv

#196 [华农兄弟] 檢查竹鼠- https://www.youtube.com/watch?v=EUR32AscCCc

#196[华农兄弟] 檢查竹鼠

---

subtitles/wang-gang/20190915-catch-bbq.txt

#185 【美食作家王刚】去华农家摸鱼烤竹鼠 - https://youtu.be/S4cHtPsK0VM

#185 【美食作家王刚】去华农家摸鱼烤竹鼠

---

subtitles/wang-gang/20190924-ma-la-niu-bian.sbv
subtitles/wang-gang/captions (1).sbv

190923-bull_pizzle

---

subtitles/hua-nong-brothers/20190928-huanong-kiwifruit.sbv

#224 [华农兄弟] 摘野生猕猴桃 - https://youtu.be/ces2YfXQjCo

[华农兄弟] 摘野生猕猴桃

---

subtitles/hua-nong-brothers/20190929-huanong-check-rats.sbv

#226 [华农兄弟] 外出归来检查竹鼠 - https://youtu.be/bPILO_IUQww

 [华农兄弟] 外出归来检查竹鼠 - https://youtu.be/bPILO_IUQww

---

subtitles/hua-nong-brothers/20190929-huanong-crabs.sbv

#227 [华农兄弟] 放地笼抓螃蟹 - https://youtu.be/ymF1s4AE50Y

[华农兄弟] 放地笼抓螃蟹

---

subtitles/hua-nong-brothers/20190929-huanong-chestnutspumpkins.sbv

#231 [华农兄弟] 摘摄影小哥家的板栗和南瓜 - https://youtu.be/fm03VRhc6kE

[华农兄弟] 摘摄影小哥家的板栗和南瓜

---

subtitles/hua-nong-brothers/20190928-six-bamboo-rats.sbv

#222 [华农兄弟] 抓6只竹鼠去王刚跟山药家玩 - https://youtu.be/siWvJ1Y4LP0

[华农兄弟] 抓6只竹鼠去王刚跟山药家玩

---

subtitles/wang-gang/190930-song-shu-wa-tu.sbv

190930-song-zhu-shu-wa-tu

---

subtitles/wang-gang/191002-tu-fei-zhu-gan.sbv

191002-tu-fei-zhu-gan

---

subtitles/wang-gang/20191004-gill-bamboo-rats.sbv

#237 【美食作家王刚】王刚华农烤竹鼠 - https://youtu.be/-kDUl2ly8LE

【美食作家王刚】王刚华农烤竹鼠

---

subtitles/hua-nong-brothers/20191004-feed-pigs.sbv

#248 [华农兄弟] 华农兄弟这只小香猪胖得跟猪一样其它都瘦了 - https://youtu.be/N3Sb6n3N66E

[华农兄弟] 华农兄弟这只小香猪胖得跟猪一样其它都瘦了

---

subtitles/hua-nong-brothers/20191005-weigh-dogs.sbv

#251 [华农兄弟] 狗子半岁抓来称重 - https://youtu.be/kcgq6MiBhV8

[华农兄弟] 狗子半岁抓来称重

---

subtitles/hua-nong-brothers/20191006-buildling-new-concentration-camp.sbv

#255 [华农兄弟] 华农兄弟去新场地做一些竹鼠池顺便去旁边的小河看一下 - https://youtu.be/jlD38Re4nrE

[华农兄弟] 华农兄弟去新场地做一些竹鼠池顺便去旁边的小河看一下

---

subtitles/wang-gang/20191007-za-cai-chao-dan.sbv

20191007-za-cai-chao-dan

---

subtitles/20191007-potatoes.sbv

#264 [华农兄弟] 华农兄弟挖点摄影小哥家的番薯刚好他女儿也来了叫她帮忙捡番薯 - https://youtu.be/ggPDz4njz8g

[华农兄弟] 华农兄弟挖点摄影小哥家的番薯刚好他女儿也来了叫她帮忙捡番薯

---

subtitles/hua-nong-brothers/20191007-neighbour-beans.sbv

#259 [华农兄弟] 华农兄弟搞点邻居大婶家的黄豆来吃放点盐煮 一煮很嫩很好吃 - https://youtu.be/Ux5Tze04ENQ

[华农兄弟] 华农兄弟搞点邻居大婶家的黄豆来吃放点盐煮 一煮很嫩很好吃

---

subtitles/hua-nong-brothers/20191008-straw.sbv

#267 [华农兄弟] 华农兄弟秋天了给母鼠放点稻草其它公鼠等冬天再放 - https://youtu.be/d9jAcVTsnwA

#[华农兄弟] 华农兄弟秋天了给母鼠放点稻草其它公鼠等冬天再放

---

subtitles/hua-nong-brothers/20191008-bead-necklace.sbv

#266 [华农兄弟] 华农兄弟老婆最近心情不好摘点草珠子做一串项链给她

[华农兄弟] 华农兄弟老婆最近心情不好摘点草珠子做一串项链给她

---

subtitles/hua-nong-brothers/20191011-cats.sbv

#276 [华农兄弟] 华农兄弟捡到2只小猫养在家里老鼠都不敢来了 - https://youtu.be/eixebWn5Puw

[华农兄弟] 华农兄弟捡到2只小猫养在家里老鼠都不敢来了

---

subtitles/hua-nong-brothers/20191013-tangpi.sbv

#287  [华农兄弟] 华农兄弟突然想吃去烫皮河边搞点沙子来炒很香哦 - https://youtu.be/p_qNwOuo_H8

[华农兄弟] 华农兄弟突然想吃去烫皮河边搞点沙子来炒很香哦

---

subtitles/hua-nong-brothers/20191014-wildfruits.sbv

#290  [华农兄弟] 华农兄弟带老弟上山砍竹子顺便看一下山上的野果熟了没有 - https://youtu.be/CY3i9OFc8PY

[华农兄弟] 华农兄弟带老弟上山砍竹子顺便看一下山上的野果熟了没有

---

subtitles/hua-nong-brothers/20191016-catchfish.sbv

#300 [华农兄弟] 华农兄弟河里面好多鱼我们去钓一下顺便网一点来吃 - https://youtu.be/tTzOhz1kzDA

[华农兄弟] 华农兄弟河里面好多鱼我们去钓一下顺便网一点来吃

---

subtitles/hua-nong-brothers/20191017-weighpig.sbv

#303 [华农兄弟] 华农兄弟摘两个西红柿来吃顺便摘点给小猪吃再抓它称一下 - https://youtu.be/EmxlMsPbfzY

[华农兄弟] 华农兄弟摘两个西红柿来吃顺便摘点给小猪吃再抓它称一下

---

subtitles/hua-nong-brothers/20191018-pumpkinchestnut.sbv

#305 [华农兄弟] 华农兄弟看一下写名字的拿藤果熟了没有顺便摘点南瓜跟玉米 - https://youtu.be/estbwzp5fvQ

[华农兄弟] 华农兄弟看一下写名字的拿藤果熟了没有顺便摘点南瓜跟玉米

---

subtitles/hua-nong-brothers/20191019-feedpigs.sbv

#311 [华农兄弟] 华农兄弟给猪打扫一下猪窝再给一些稻草跟南瓜给它们 - https://youtu.be/Q5J5vgYMt0c

[华农兄弟] 华农兄弟给猪打扫一下猪窝再给一些稻草跟南瓜给它们

---

subtitles/hua-nong-brothers/20191020-feed-bamboorats.sbv

#317 [华农兄弟] 华农兄弟竹鼠日常喂养喂点米糠拌饭看它们吃得多开心 - https://youtu.be/NiVVNa1O3aY

[华农兄弟] 华农兄弟竹鼠日常喂养喂点米糠拌饭看它们吃得多开心

---

subtitles/hua-nong-brothers/20191020-fix-gates.sbv

#316 [华农兄弟] 华农兄弟铁门烂掉了我们用铁丝绑一下避免狗子到处乱跑 - https://youtu.be/CET3GzrKipU

[华农兄弟] 华农兄弟铁门烂掉了我们用铁丝绑一下避免狗子到处乱跑

---

subtitles/wang-gang/191022-fried-meatballs.sbv

 191022-fried-meatballs

---

subtitles/hua-nong-brothers/20191022-chopbamboo.sbv

#321 华农兄弟] 华农兄弟帮房东把山上的小竹子砍掉拿去喂我们家的竹鼠 - https://youtu.be/0Az2NrrB074

[华农兄弟] 华农兄弟帮房东把山上的小竹子砍掉拿去喂我们家的竹鼠

---

subtitles/hua-nong-brothers/20191025-vegatables.sbv

#327 [华农兄弟] 华农兄弟发现在路边好多青菜摘点来吃顺便再摘点黄豆和萝卜 - https://youtu.be/e9irQlQKjpU

[华农兄弟] 华农兄弟发现在路边好多青菜摘点来吃顺便再摘点黄豆和萝卜

---

subtitles/hua-nong-brothers/20191025-mice.sbv

#329 [华农兄弟] 华农兄弟竹鼠和老鼠放一起会怎么样上山抓只老鼠回来试一下 - https://youtu.be/1q-KaJEG7CA

[华农兄弟] 华农兄弟竹鼠和老鼠放一起会怎么样上山抓只老鼠回来试一下

---

subtitles/hua-nong-brothers/20191027-wildfruits.sbv

#335 [华农兄弟] 华农兄弟山上的一些野果熟了叫上兄弟们一去边摘边吃 - https://youtu.be/27fzfXRVd2A

[华农兄弟] 华农兄弟山上的一些野果熟了叫上兄弟们一去边摘边吃

---

subtitles/wang-gang/191027-cola-chicken-wings.sbv

191027-Cola-Chicken-Wings

---

subtitles/hua-nong-brothers/20191028-catchfish.sbv
subtitles/hua-nong-brothers/captions (10).sbv

#341 [华农兄弟] 华农兄弟去兄弟家的池塘钓鱼钓了一会钓不到幸好带了抽水机 - https://youtu.be/HoqpY_nvrY4

[华农兄弟] 华农兄弟去兄弟家的池塘钓鱼钓了一会钓不到幸好带了抽水机

---

subtitles/hua-nong-brothers/20191029-navaloranges.sbv

#342 [华农兄弟] 华农兄弟参观5000亩的赣南脐橙产业园再找兄弟要点脐橙送粉丝 - https://youtu.be/_7MTQNBLsDw

[华农兄弟] 华农兄弟参观5000亩的赣南脐橙产业园再找兄弟要点脐橙送粉丝

---

subtitles/hua-nong-brothers/20191029-puppies.sbv

#346 [华农兄弟] 华农兄弟老弟带回来7只小狗这下真的是一地都是狗了 - https://youtu.be/mXS8wLauDns

[华农兄弟] 华农兄弟老弟带回来7只小狗这下真的是一地都是狗了

---

subtitles/hua-nong-brothers/20191030-wasp-nest.sbv

#350 [华农兄弟] 华农兄弟把新场地的黄蜂窝搞掉不然到时候住人会被蜇 - https://youtu.be/RQalc8i25pw

[华农兄弟] 华农兄弟把新场地的黄蜂窝搞掉不然到时候住人会被蜇

---

subtitles/hua-nong-brothers/20191031-meal.sbv

#355 [华农兄弟] 华农兄弟平时在家随便搞点菜吃今天兄弟来了多煎两个蛋 - https://youtu.be/PqhvD6SYCV8

[华农兄弟] 华农兄弟平时在家随便搞点菜吃今天兄弟来了多煎两个蛋

---

subtitles/hua-nong-brothers/20191104-fruits.sbv

#364 [华农兄弟] 华农兄弟摘点老王家的柿子尝一下顺便再去摘点野果 - https://youtu.be/x09aYfC7l6M

[华农兄弟] 华农兄弟摘点老王家的柿子尝一下顺便再去摘点野果

---

subtitles/hua-nong-brothers/20191108-oriental-raisins.sbv

#373 [华农兄弟] 华农兄弟捡点拐枣泡酒路过兄弟的玉米地搞点来喂猪 - https://youtu.be/e66aOy8f8PA

[华农兄弟] 华农兄弟捡点拐枣泡酒路过兄弟的玉米地搞点来喂猪

---

subtitles/hua-nong-brothers/20191108-relocate-rats.sbv

#372 [华农兄弟] 华农兄弟把兄弟家的竹鼠通通搬到我们新场房去还有花竹鼠哦 - https://youtu.be/Hq2jso2Yhdw

[华农兄弟] 华农兄弟把兄弟家的竹鼠通通搬到我们新场房去还有花竹鼠哦

---

subtitles/hua-nong-brothers/20191110-naveloranges.sbv

#380 [华农兄弟] 华农兄弟看一下我们家的脐橙熟了没有顺便摘一点回去吃 - https://youtu.be/pDWKWbIb9TQ

[华农兄弟] 华农兄弟看一下我们家的脐橙熟了没有顺便摘一点回去吃

---

subtitles/wang-gang/191112-La-Zhu-Shu.sbv

191112-la-zhu-shu

---

subtitles/hua-nong-brothers/20191115-manydogs.sbv

#395 [华农兄弟] 华农兄弟小狗又胖了狗妈妈又怀孕了这下真的一地都是狗了 - https://youtu.be/KtUF2vAakhQ

[华农兄弟] 华农兄弟小狗又胖了狗妈妈又怀孕了这下真的一地都是狗了

---

subtitles/hua-nong-brothers/20191115-persimmons.sbv

#394 [华农兄弟] 华农兄弟兄弟家的油柿子熟了一树都是带老弟去摘点 - https://youtu.be/lCQj1ynbyRg

[华农兄弟] 华农兄弟兄弟家的油柿子熟了一树都是带老弟去摘点

---

subtitles/hua-nong-brothers/20191119-red-elephant-grass.sbv

#401 401[华农兄弟] 华农兄弟砍点场里的红象草喂竹鼠看它们抢来抢去的很喜欢吃 - https://youtu.be/V4elakVwR5s

[华农兄弟] 华农兄弟砍点场里的红象草喂竹鼠看它们抢来抢去的很喜欢吃

---

subtitles/hua-nong-brothers/20191119-Guagua-Fatties.sbv

#403 [华农兄弟] 华农兄弟瓜瓜瘦了差点认不出来了小胖却越来越胖了https://youtu.be/XD3rQewNubE

[华农兄弟] 华农兄弟瓜瓜瘦了差点认不出来了小胖却越来越胖了

---

subtitles/hua-nong-brothers/20191121-oranges-tianlungshan.txt

#415 [华农兄弟] 华农兄弟参加赣南脐橙比赛拿了个第一顺便去天龙山玩了一下 - https://youtu.be/30wo279KYdQ

[华农兄弟] 华农兄弟参加赣南脐橙比赛拿了个第一顺便去天龙山玩了一下

---

subtitles/hua-nong-brothers/20191122-pigs.sbv

#417 [华农兄弟] 华农兄弟把全部猪放出来散养摸一下大公猪它竟然想咬我 - https://youtu.be/cL7_eCamawI

[华农兄弟] 华农兄弟把全部猪放出来散养摸一下大公猪它竟然想咬我

---

subtitles/20191124-puppies.sbv

#419 [华农兄弟] 华农兄弟天气越来越冷了老弟给小狗买了几件衣服给它们穿上 - https://youtu.be/zOfa4oXVHco

[华农兄弟] 华农兄弟天气越来越冷了老弟给小狗买了几件衣服给它们穿上

---

subtitles/hua-nong-brothers/20191126-fish-dogs-pigs.sbv

#424 [华农兄弟] 华农兄弟一年又快过去了兄弟家野池塘的鱼也长大了网点来煎 - https://youtu.be/G5ig69mzlmE

[华农兄弟] 华农兄弟一年又快过去了兄弟家野池塘的鱼也长大了网点来煎

---

subtitles/hua-nong-brothers/20191127-puppes-pigs.sbv

#427 [华农兄弟] 华农兄弟狗子又下崽了带大家看一下顺便给香猪喂点酒糟 - https://youtu.be/l2L-SkIlrEY

[华农兄弟] 华农兄弟狗子又下崽了带大家看一下顺便给香猪喂点酒糟

---

subtitles/hua-nong-brothers/20191128-pigs.sbv

#433 [华农兄弟] 华农兄弟把小猪放出来了它又可以跟狗子们一起吃喝玩乐了 - https://youtu.be/0r13IZh9fuk

[华农兄弟] 华农兄弟把小猪放出来了它又可以跟狗子们一起吃喝玩乐了

---

subtitles/hua-nong-brothers/20191128-feed-dogs.sbv

#430 [华农兄弟] 华农兄弟喂点粉丝送的狗粮给狗子吃看它们抢来抢去好像很好吃 - https://youtu.be/LvCqcuUxRB4

[华农兄弟] 华农兄弟喂点粉丝送的狗粮给狗子吃看它们抢来抢去好像很好吃

---

subtitles/hua-nong-brothers/20191129-kill-pigs.sbv

#435 华农兄弟：猪吃酒糟醉了，叫兄弟帮忙一起宰猪，烤起来很香哦 https://www.youtube.com/watch?v=xkSxAypC0Wk

[华农兄弟] 华农兄弟猪吃酒糟醉了叫兄弟帮忙一起宰猪烤起来很香哦

---

subtitles/hua-nong-brothers/20191201-kudzu-root-worms.sbv

#443 [华农兄弟] 华农兄弟搞了一点葛根虫子用油一炸嘎嘣脆很好吃哦 - https://youtu.be/x2XKYmCXNNY

[华农兄弟] 华农兄弟搞了一点葛根虫子用油一炸嘎嘣脆很好吃哦

---

subtitles/hua-nong-brothers/20191130-piglets.sbv

#441 [华农兄弟] 华农兄弟场里的橘子快熟了摘一个尝一下顺便看一下小猪崽 - https://youtu.be/witP5dfYDDA

[华农兄弟] 华农兄弟场里的橘子快熟了摘一个尝一下顺便看一下小猪崽

---

subtitles/hua-nong-brothers/20191130-puppies.sbv

#439 [华农兄弟] 华农兄弟天气越来越冷了给小狗子做一个温暖的窝 - https://youtu.be/JVlyc7UBDrQ

[华农兄弟] 华农兄弟天气越来越冷了给小狗子做一个温暖的窝

---

subtitles/wang-gang/191202-huang-men-ji.sbv

191201-huang-men-ji

---

subtitles/hua-nong-brothers/20191206-grill-with-wanggang.sbv

#454 [华农兄弟] 华农兄弟抓了只鸡刚好兄弟来了一起烤鸡顺便再烤点排骨 - https://youtu.be/jPIvW8B18-s

[华农兄弟] 华农兄弟抓了只鸡刚好兄弟来了一起烤鸡顺便再烤点排骨

---

subtitles/hua-nong-brothers/20191207-grill-with-huanong.txt

#457 【美食作家王刚】烤鸡烤猪排 - https://youtu.be/aUBTGWlyxFM

【美食作家王刚】烤鸡烤猪排 - https://youtu.be/aUBTGWlyxFM

---

subtitles/wang-gang/20191207-visit-huanong.txt

#455 【美食作家王刚】参观兄弟家的猪和竹鼠 - https://youtu.be/z0M01HwpnM4

【美食作家王刚】参观兄弟家的猪和竹鼠 - https://youtu.be/z0M01HwpnM4

---

subtitles/hua-nong-brothers/20191207-kuduz-root-soup.sbv

#459 [华农兄弟] 华农兄弟最近天气干燥摄影小哥又上火了挖点葛根来炖竹鼠 - https://youtu.be/ST6Ne5xZ7F4

[华农兄弟] 华农兄弟最近天气干燥摄影小哥又上火了挖点葛根来炖竹鼠

---

subtitles/hua-nong-brothers/20191209-puppies-piglets.sbv

#466 [华农兄弟] 华农兄弟才十几天小狗子和小猪崽就长肥了不少胖墩墩的 - https://youtu.be/d49K5I_xGkY

[华农兄弟] 华农兄弟才十几天小狗子和小猪崽就长肥了不少胖墩墩的

---

subtitles/hua-nong-brothers/20191210-roast-chicken.sbv

#472 [华农兄弟] 华农兄弟抬了个兄弟家的烤炉回来顺便再去抓只兄弟家的鸡来烤 - https://youtu.be/wde3Qm5K6Zo

[华农兄弟] 华农兄弟抬了个兄弟家的烤炉回来顺便再去抓只兄弟家的鸡来烤

---

subtitles/hua-nong-brothers/20191213-fish-permissons.sbv

#478 [华农兄弟] 华农兄弟先把兄弟送的红鲤鱼放池子里养着再去摘点他家的柿子来吃 - https://youtu.be/LBztNyvKWuo

[华农兄弟] 华农兄弟先把兄弟送的红鲤鱼放池子里养着再去摘点他家的柿子来吃

---

subtitles/hua-nong-brothers/20191214-worms.sbv

#483 [华农兄弟] 华农兄弟又到了吃虫子的季节放点孜然烤一烤又香又脆很美味哦 - https://youtu.be/LPitnZrvZ7U

[华农兄弟] 华农兄弟又到了吃虫子的季节放点孜然烤一烤又香又脆很美味哦

---

subtitles/hua-nong-brothers/20191215-puppies.sbv

#492 [华农兄弟] 华农兄弟小狗子已经睁眼会爬了把它们捉出来晒晒太阳 - https://youtu.be/gb7KHILMdCs

[华农兄弟] 华农兄弟小狗子已经睁眼会爬了把它们捉出来晒晒太阳

---

subtitles/hua-nong-brothers/20191215-passion-fruits.sbv

#488 [华农兄弟] 华农兄弟兄弟家地里长了很多野生的百香果摘两个来尝一下 - https://youtu.be/DTGR_yy6L2M

[华农兄弟] 华农兄弟兄弟家地里长了很多野生的百香果摘两个来尝一下

---

subtitles/hua-nong-brothers/20191216-chickens-mushrooms.sbv

#497 [华农兄弟] 华农兄弟摘点大叔家的香菇捉2只兄弟家的小鸡做美味的小鸡炖蘑菇 - https://youtu.be/op3VNF-4kZM

[华农兄弟] 华农兄弟摘点大叔家的香菇捉2只兄弟家的小鸡做美味的小鸡炖蘑菇

---

subtitles/hua-nong-brothers/20191217-eggs.sbv

#499 [华农兄弟] 华农兄弟老妈养的鸡下了不少蛋其中几个像小鸟蛋一样大 - https://youtu.be/WDBU2RgjjZE

[华农兄弟] 华农兄弟老妈养的鸡下了不少蛋其中几个像小鸟蛋一样大

---

subtitles/wang-gang/191218-techniques for processing por tripe
subtitles/wang-gang/191218-techniques-for-processing-por-tripe.sbv

Create 191218-techniques for processing pork tripe

---

subtitles/hua-nong-brothers/20191220-feed-pigs.sbv

#506 [华农兄弟] 华农兄弟喂点网友送的猪饲料给小猪吃顺便捉只猪崽玩一下 - https://youtu.be/MwCNR2pZ4vw

[华农兄弟] 华农兄弟喂点网友送的猪饲料给小猪吃顺便捉只猪崽玩一下

---

subtitles/hua-nong-brothers/20191220-weigh-dogs.sbv

#509 [华农兄弟] 华农兄弟称一下养了几个小月的小狗子看起来小称起来还挺重的 - https://youtu.be/kp5JRMzL1-o

[华农兄弟] 华农兄弟称一下养了几个小月的小狗子看起来小称起来还挺重的

---

subtitles/hua-nong-brothers/20191221-check-bamboo-rats.sbv

#511 [华农兄弟] 华农兄弟天冷看一下竹鼠有没有感冒顺便丢点稻草给猪做窝 - https://youtu.be/OJDHNivX19s

[华农兄弟] 华农兄弟天冷看一下竹鼠有没有感冒顺便丢点稻草给猪做窝

---

subtitles/hua-nong-brothers/20191224-bamboo-shoots.sbv

#517 [华农兄弟] 华农兄弟上山砍竹子顺便挖点竹笋回去炒腊肉很好吃哦 - https://youtu.be/2f687b0M2W

[华农兄弟] 华农兄弟上山砍竹子顺便挖点竹笋回去炒腊肉很好吃哦

---

subtitles/hua-nong-brothers/2191225-elephant-grass-radish.sbv

#523 [华农兄弟] 华农兄弟看一下被霜打死的象草再去拔几个老弟种得萝卜来吃 - https://youtu.be/eAM6tmkN-z4

[华农兄弟] 华农兄弟看一下被霜打死的象草再去拔几个老弟种得萝卜来吃

---

subtitles/hua-nong-brothers/20191226-tea-mangosteen.sbv

#526 [华农兄弟] 华农兄弟摘几朵茶花尝一下再去摘点竹节果尝一下 - https://youtu.be/RkljEo0cZQ8

[华农兄弟] 华农兄弟摘几朵茶花尝一下再去摘点竹节果尝一下

---

subtitles/hua-nong-brothers/20191228-bamoo-shoots-bamboo-rats.sbv

#529 [华农兄弟] 华农兄弟有只竹鼠托梦给我想吃竹笋去挖个来炖它 - https://youtu.be/FzDpGodmCnc

[华农兄弟] 华农兄弟有只竹鼠托梦给我想吃竹笋去挖个来炖它

---

subtitles/20191231-puppies.sbv

#538 [华农兄弟] 华农兄弟天气不错把小狗抱到楼下来玩肥肥的很可爱 - https://youtu.be/utIjUZXw8nw

[华农兄弟] 华农兄弟天气不错把小狗抱到楼下来玩肥肥的很可爱

---

subtitles/hua-nong-brothers/20200102-pigs.sbv

#545 [华农兄弟] 华农兄弟关着的猪一下没注意跑出来好几条看到什么都吃 - https://youtu.be/TTq9o0NmHbc

[华农兄弟] 华农兄弟关着的猪一下没注意跑出来好几条看到什么都吃

---

subtitles/hua-nong-brothers/20200103-pigs.sbv

#550 [华农兄弟] 华农兄弟搞点米糠拌饭把小猪骗回去再把猪栏修一下 - https://youtu.be/B-TE9-bSI9k

[华农兄弟] 华农兄弟搞点米糠拌饭把小猪骗回去再把猪栏修一下

---

subtitles/hua-nong-brothers/20200104-tinted-bamboo-rats.sbv

#556 [华农兄弟] 华农兄弟带大家看一下花竹鼠顺便看一下它的崽很漂亮哦 - https://youtu.be/uadvt8DNsE8

[华农兄弟] 华农兄弟带大家看一下花竹鼠顺便看一下它的崽很漂亮哦

---

subtitles/hua-nong-brothers/20200106-feed-pigs.sbv

#563 [华农兄弟] 华农兄弟猪又跑出来了没办法只好喂点好吃的给它们 - https://youtu.be/G34RZK9btgw

[华农兄弟] 华农兄弟猪又跑出来了没办法只好喂点好吃的给它们

---

subtitles/wang-gang/200106-la-shao-jia-yu.sbv

Upload la shao jia yu

---

subtitles/xue-yu/20200104-roast-geese.srt
subtitles/xue-yu/roast geese

【雪鱼】烧鹅-https://youtu.be/NIY6aPsSe3s

---

subtitles/wang-gang/200110-xian-shao-bai.sbv

200110-xian-shao-bai.sbv

---

subtitles/wang-gang/200120-kao-yu.sbv

kao-yu finished

---

subtitles/wang-gang/200122-xie-dui-lian.sbv

#597 
太难了，请大家多提对联翻译意见 & 一些地方拿不准已标注

200122-xie-dui-lian

---

subtitles/wang-gang/20200125-ba-ba-banquet.sbv

#611 【美食作家王刚】坝坝宴 - https://youtu.be/3V9fkm4wZN0

【美食作家王刚】坝坝宴 - https://youtu.be/3V9fkm4wZN0

---

subtitles/lao-fan-gu/README.md

老饭骨的视频描述有一段固定的内容。
这段翻译是运营团队提供的，求审核

添加老饭骨视频描述中固定部分的翻译

---

subtitles/lao-fan-gu/200229-chu-yi-de-jiao-zi.sbv

[老饭骨] 初一的饺子

---

subtitles/hua-nong-brothers/20200423-orchid.sbv

[华农兄弟] 华农兄弟参观一下兄弟家的兰花基地各种兰花很漂亮哦 - https://youtu.be/Bg35GtTMdbQ
#954

[华农兄弟] 华农兄弟参观一下兄弟家的兰花基地各种兰花很漂亮哦 - https://youtu.be/Bg35GtTMdbQ
